const SB='https://eppyjmtowtkxcwwhvwzp.supabase.co';
const KEY='sb_publishable_3oEkPaexOGYojb-9imVJjw_2SCQ7WRr';
const cache=new Map();
function norm(v){return String(v||'').trim().replace(/\s+/g,'')}
function digits(v){return norm(v).replace(/\D/g,'')}
function clean(v){return v===null||v===undefined?'':String(v).trim()}
function number(v){const n=Number(v);return Number.isFinite(n)?n:null}
async function getJson(url,headers={},timeout=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers,signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
function historyValue(row,key){const i=row&&row.input_data&&typeof row.input_data==='object'?row.input_data:{};return i[key]!==undefined&&i[key]!==null&&i[key]!==''?i[key]:row?.[key]}
async function historyLookup(code,auth){try{const q=new URLSearchParams({select:'cadastral_code,city,address,latitude,longitude,land_area,house_area,input_data,created_at',cadastral_code:'eq.'+code,order:'created_at.desc',limit:'5'});const headers={apikey:KEY,Authorization:auth&&/^Bearer\s+/i.test(auth)?auth:'Bearer '+KEY};const rows=await getJson(SB+'/rest/v1/property_valuations?'+q.toString(),headers,4500);if(!Array.isArray(rows)||!rows.length)return null;const row=rows.find(r=>clean(historyValue(r,'address')))||rows[0];return{city:clean(historyValue(row,'city')),address:clean(historyValue(row,'address')),latitude:number(historyValue(row,'latitude')),longitude:number(historyValue(row,'longitude')),land_area:number(historyValue(row,'land_area')),house_area:number(historyValue(row,'house_area')),source:'history'}}catch(e){return null}}
function centroid(g){if(!g)return null;if(Number.isFinite(Number(g.x))&&Number.isFinite(Number(g.y)))return{longitude:Number(g.x),latitude:Number(g.y)};const rings=Array.isArray(g.rings)?g.rings:[];let sx=0,sy=0,n=0;for(const ring of rings)for(const p of ring||[]){const x=Number(p?.[0]),y=Number(p?.[1]);if(Number.isFinite(x)&&Number.isFinite(y)){sx+=x;sy+=y;n++}}return n?{longitude:sx/n,latitude:sy/n}:null}
async function arcgisFind(code){const services=['https://gisserver.mepa.gov.ge/arcgis/rest/services/NAPR_DATA/NaprParcelsMap/MapServer/find','https://gisserver.mepa.gov.ge/arcgis/rest/services/%E1%83%A4%E1%83%94%E1%83%9C%E1%83%94%E1%83%91%E1%83%98/MapServer/find','https://gisserver.mepa.gov.ge/arcgis/rest/services/TOOLS_NEW/MapServer/find'];const variants=[norm(code),digits(code)].filter((v,i,a)=>v&&a.indexOf(v)===i);for(const base of services){for(const v of variants){try{const q=new URLSearchParams({searchText:v,contains:'false',searchFields:'REG_N',returnGeometry:'true',sr:'4326',f:'json'});const d=await getJson(base+'?'+q.toString(),{},5000);const results=Array.isArray(d?.results)?d.results:[];const hit=results.find(r=>{const a=r.attributes||{},reg=clean(a.REG_N||a.reg_n||r.value);return digits(reg)===digits(code)})||results[0];if(!hit)continue;const c=centroid(hit.geometry),a=hit.attributes||{},area=number(a['SHAPE.STArea()']??a.SHAPE_STArea??a.AREA??a.area);return{coordinates:c,land_area:area&&area>1?Math.round(area*100)/100:null,source:'napr-map'}}catch(e){}}}return null}
function cityFromAddress(a={}){const vals=[a.city,a.town,a.village,a.municipality,a.county,a.state_district,a.suburb].map(clean).filter(Boolean),hay=vals.join(' ').toLowerCase();if(/surami|сурами|სურამი/.test(hay))return'Сурами';if(/khashuri|хашури|ხაშური/.test(hay))return'Хашури';return clean(a.city||a.town||a.village||a.municipality||a.county)}
function exactAddress(d){const a=d?.address||{},road=clean(a.road||a.pedestrian||a.residential||a.neighbourhood||a.suburb),house=clean(a.house_number);if(road)return(road+(house?', '+house:'')).trim();const parts=clean(d?.display_name).split(',').map(s=>s.trim()).filter(Boolean);return parts.slice(0,Math.min(3,parts.length)).join(', ')}
async function reverseGeocode(c){if(!c||!Number.isFinite(c.latitude)||!Number.isFinite(c.longitude)||Math.abs(c.latitude)>90||Math.abs(c.longitude)>180)return null;try{const q=new URLSearchParams({lat:String(c.latitude),lon:String(c.longitude),format:'jsonv2',addressdetails:'1',zoom:'18','accept-language':'ru,ka,en'});const d=await getJson('https://nominatim.openstreetmap.org/reverse?'+q.toString(),{'User-Agent':'KhashuriMarketplace/1.0 (https://khashuri-marketplace.vercel.app)','Referer':'https://khashuri-marketplace.vercel.app/'},5500);return{city:cityFromAddress(d?.address||{}),address:exactAddress(d)}}catch(e){return null}}
async function lookup(code,auth=''){code=norm(code);if(!code||digits(code).length<8)return{ok:false,error:'invalid_cadastral_code'};const key=digits(code),cached=cache.get(key);if(cached&&Date.now()-cached.at<30*60*1000)return cached.data;const [history,parcel]=await Promise.all([historyLookup(code,auth),arcgisFind(code)]);let geo=null;if(parcel?.coordinates)geo=await reverseGeocode(parcel.coordinates);const data={ok:!!(parcel||history),cadastral_code:code,parcel_found:!!parcel,city:clean(geo?.city||history?.city),address:clean(history?.address||geo?.address),latitude:number(parcel?.coordinates?.latitude??history?.latitude),longitude:number(parcel?.coordinates?.longitude??history?.longitude),land_area:number(parcel?.land_area??history?.land_area),source:parcel?(geo?'napr+geocode':'napr-map'):(history?'history':'none')};cache.set(key,{at:Date.now(),data});return data}
module.exports={lookup};
