const SB='https://eppyjmtowtkxcwwhvwzp.supabase.co';
const KEY='sb_publishable_3oEkPaexOGYojb-9imVJjw_2SCQ7WRr';
const cache=new Map();
function norm(v){return String(v||'').trim().replace(/\s+/g,'')}
function digits(v){return norm(v).replace(/\D/g,'')}
function clean(v){return v===null||v===undefined?'':String(v).trim()}
function number(v){const n=Number(v);return Number.isFinite(n)?n:null}
function rounded(v){const n=number(v);return n&&n>0?Math.round(n*100)/100:null}
async function getJson(url,headers={},timeout=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers,signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
function inputOf(row){return row&&row.input_data&&typeof row.input_data==='object'?row.input_data:{}}
function historyValue(row,key){const i=inputOf(row);return i[key]!==undefined&&i[key]!==null&&i[key]!==''?i[key]:row?.[key]}
function historyExtras(row){const i=inputOf(row),u=i.utilities&&typeof i.utilities==='object'?i.utilities:{};return{
 floor_count:number(i.floor_count),land_purpose:clean(i.land_purpose),build_year:number(i.build_year),material:clean(i.material),rooms:number(i.rooms),bedrooms:number(i.bedrooms),bathrooms:number(i.bathrooms),heating:clean(i.heating),lot_frontage:number(i.lot_frontage),lot_depth:number(i.lot_depth),lot_shape:clean(i.lot_shape),terrain:clean(i.terrain),road_type:clean(i.road_type),commercial_potential:clean(i.commercial_potential),structural_condition:clean(i.structural_condition),basement:typeof i.basement==='boolean'?i.basement:null,garage:typeof i.garage==='boolean'?i.garage:null,balcony:typeof i.balcony==='boolean'?i.balcony:null,utilities:{gas:typeof u.gas==='boolean'?u.gas:null,water:typeof u.water==='boolean'?u.water:null,sewer:typeof u.sewer==='boolean'?u.sewer:null,electricity:typeof u.electricity==='boolean'?u.electricity:null,internet:typeof u.internet==='boolean'?u.internet:null}
}}
async function historyLookup(code,auth){try{const q=new URLSearchParams({select:'cadastral_code,city,address,latitude,longitude,land_area,house_area,input_data,created_at',cadastral_code:'eq.'+code,order:'created_at.desc',limit:'8'});const headers={apikey:KEY,Authorization:auth&&/^Bearer\s+/i.test(auth)?auth:'Bearer '+KEY};const rows=await getJson(SB+'/rest/v1/property_valuations?'+q.toString(),headers,4500);if(!Array.isArray(rows)||!rows.length)return null;const best=rows.find(r=>clean(historyValue(r,'address'))&&number(historyValue(r,'house_area')))||rows.find(r=>number(historyValue(r,'house_area')))||rows[0];return{city:clean(historyValue(best,'city')),address:clean(historyValue(best,'address')),latitude:number(historyValue(best,'latitude')),longitude:number(historyValue(best,'longitude')),land_area:rounded(historyValue(best,'land_area')),house_area:rounded(historyValue(best,'house_area')),extras:historyExtras(best),source:'history'}}catch(e){return null}}
function centroid(g){if(!g)return null;if(Number.isFinite(Number(g.x))&&Number.isFinite(Number(g.y)))return{longitude:Number(g.x),latitude:Number(g.y)};const rings=Array.isArray(g.rings)?g.rings:[];let sx=0,sy=0,n=0;for(const ring of rings)for(const p of ring||[]){const x=Number(p?.[0]),y=Number(p?.[1]);if(Number.isFinite(x)&&Number.isFinite(y)){sx+=x;sy+=y;n++}}return n?{longitude:sx/n,latitude:sy/n}:null}
function parseLandPurpose(attrs={}){const txt=Object.entries(attrs).map(([k,v])=>k+' '+clean(v)).join(' ').toLowerCase();if(/არასასოფლო|non[- _]?agric|несельск/.test(txt))return'non_agricultural';if(/სასოფლო|agricultur|сельскохозяй/.test(txt))return'agricultural';return''}
async function arcgisFind(code){const services=['https://gisserver.mepa.gov.ge/arcgis/rest/services/NAPR_DATA/NaprParcelsMap/MapServer/find','https://gisserver.mepa.gov.ge/arcgis/rest/services/%E1%83%A4%E1%83%94%E1%83%9C%E1%83%94%E1%83%91%E1%83%98/MapServer/find','https://gisserver.mepa.gov.ge/arcgis/rest/services/TOOLS_NEW/MapServer/find'];const variants=[norm(code),digits(code)].filter((v,i,a)=>v&&a.indexOf(v)===i);for(const base of services){for(const v of variants){try{const q=new URLSearchParams({searchText:v,contains:'false',searchFields:'REG_N',returnGeometry:'true',sr:'4326',f:'json'});const d=await getJson(base+'?'+q.toString(),{},5000);const results=Array.isArray(d?.results)?d.results:[];const hit=results.find(r=>{const a=r.attributes||{},reg=clean(a.REG_N||a.reg_n||r.value);return digits(reg)===digits(code)})||results[0];if(!hit)continue;const c=centroid(hit.geometry),a=hit.attributes||{},area=rounded(a['SHAPE.STArea()']??a.SHAPE_STArea??a.AREA??a.area);return{coordinates:c,land_area:area,land_purpose:parseLandPurpose(a),geometry:hit.geometry,attributes:a,source:'napr-map'}}catch(e){}}}return null}
function buildingAreaFromFeature(f){const a=f?.attributes||{};const footprint=rounded(a['SHAPE.STArea()']??a.SHAPE_STArea??a.AREA??a.area);if(!footprint)return null;let floors=Number(a.SARTULIANOBA??a.FLOORS??a.floor_count??1);if(!Number.isFinite(floors)||floors<1||floors>10)floors=1;return{area:rounded(footprint*floors),footprint,floors,id:clean(a.SENOBA_ID||a.UNIQ_CODE||a.OBJECTID)}}
async function buildingLookup(parcel){if(!parcel?.geometry?.rings?.length)return null;const services=['https://gisserver.mepa.gov.ge/arcgis/rest/services/%E1%83%A4%E1%83%94%E1%83%9C%E1%83%94%E1%83%91%E1%83%98/MapServer/5/query','https://gisserver.mepa.gov.ge/arcgis/rest/services/TOOLS_NEW/MapServer/5/query'];const geometry=JSON.stringify({rings:parcel.geometry.rings,spatialReference:{wkid:4326}});for(const base of services){try{const q=new URLSearchParams({geometry,geometryType:'esriGeometryPolygon',inSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'OBJECTID,SENOBA_ID,UNIQ_CODE,SARTULIANOBA,FLOORS,SHAPE.STArea()',returnGeometry:'false',f:'json'});const d=await getJson(base+'?'+q.toString(),{},5000);const rows=(Array.isArray(d?.features)?d.features:[]).map(buildingAreaFromFeature).filter(Boolean).filter(x=>x.area>=5);if(!rows.length)continue;rows.sort((a,b)=>b.area-a.area);return{house_area:rows[0].area,floor_count:rows[0].floors,building_count:rows.length,main_building:rows[0],source:'napr-buildings'}}catch(e){}}return null}
function cityFromAddress(a={}){const vals=[a.city,a.town,a.village,a.municipality,a.county,a.state_district,a.suburb].map(clean).filter(Boolean),hay=vals.join(' ').toLowerCase();if(/surami|сурами|სურამი/.test(hay))return'Сурами';if(/khashuri|хашури|ხაშური/.test(hay))return'Хашури';return clean(a.city||a.town||a.village||a.municipality||a.county)}
function exactAddress(d){const a=d?.address||{},road=clean(a.road||a.pedestrian||a.residential||a.neighbourhood||a.suburb),house=clean(a.house_number);if(road)return(road+(house?', '+house:'')).trim();const parts=clean(d?.display_name).split(',').map(s=>s.trim()).filter(Boolean);return parts.slice(0,Math.min(3,parts.length)).join(', ')}
async function reverseGeocode(c){if(!c||!Number.isFinite(c.latitude)||!Number.isFinite(c.longitude)||Math.abs(c.latitude)>90||Math.abs(c.longitude)>180)return null;try{const q=new URLSearchParams({lat:String(c.latitude),lon:String(c.longitude),format:'jsonv2',addressdetails:'1',zoom:'18','accept-language':'ru,ka,en'});const d=await getJson('https://nominatim.openstreetmap.org/reverse?'+q.toString(),{'User-Agent':'KhashuriMarketplace/1.0 (https://khashuri-marketplace.vercel.app)','Referer':'https://khashuri-marketplace.vercel.app/'},5500);return{city:cityFromAddress(d?.address||{}),address:exactAddress(d)}}catch(e){return null}}
async function lookup(code,auth=''){code=norm(code);if(!code||digits(code).length<8)return{ok:false,error:'invalid_cadastral_code'};const key=digits(code),cached=cache.get(key);if(cached&&Date.now()-cached.at<30*60*1000)return cached.data;const [history,parcel]=await Promise.all([historyLookup(code,auth),arcgisFind(code)]);const [geo,building]=await Promise.all([parcel?.coordinates?reverseGeocode(parcel.coordinates):null,parcel?.geometry?buildingLookup(parcel):null]);const hx=history?.extras||{};const houseArea=history?.house_area||building?.house_area||null;const landArea=parcel?.land_area||history?.land_area||null;const floorCount=hx.floor_count||building?.floor_count||null;const landPurpose=parcel?.land_purpose||hx.land_purpose||'';const data={ok:!!(parcel||history),cadastral_code:code,parcel_found:!!parcel,city:clean(geo?.city||history?.city),address:clean(history?.address||geo?.address),latitude:number(parcel?.coordinates?.latitude??history?.latitude),longitude:number(parcel?.coordinates?.longitude??history?.longitude),land_area:rounded(landArea),house_area:rounded(houseArea),floor_count:number(floorCount),land_purpose:clean(landPurpose),house_area_source:history?.house_area?'history':(building?.house_area?'napr-buildings':'none'),floor_count_source:hx.floor_count?'history':(building?.floor_count?'napr-buildings':'none'),land_area_source:parcel?.land_area?'napr-parcel':(history?.land_area?'history':'none'),land_purpose_source:parcel?.land_purpose?'napr-parcel':(hx.land_purpose?'history':'none'),building_count:building?.building_count||null,history_fields:history?hx:null,source:parcel?(geo?'napr+geocode':'napr-map'):(history?'history':'none')};cache.set(key,{at:Date.now(),data});return data}
module.exports={lookup};
