const UPSTREAM='https://eppyjmtowtkxcwwhvwzp.supabase.co/functions/v1/khashuri-app-v12/';
const RAW='https://raw.githubusercontent.com/zurabsamkharadze-png/khashuri-marketplace/main/public/';
const ORIGIN='https://khashuri-marketplace.vercel.app';
const SB='https://eppyjmtowtkxcwwhvwzp.supabase.co';
const ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJlIiwicmVmIjoiZXBweWptdG93dGt4Y3d3aHZ3enAiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTc4NzI0MzQ3MSwiZXhwIjoyMTAyODE5NDcxfQ.FBxRhLMZgObwy5cofdKs4k0nsDxr-LhUqu3R30uwIfk';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
async function sbGet(path){const r=await fetch(SB+'/rest/v1/'+path,{headers:{apikey:ANON,Authorization:'Bearer '+ANON,Accept:'application/json'}});if(!r.ok)return null;const a=await r.json();return a&&a[0]||null}
async function publicListing(id){return sbGet(`classified_listings?id=eq.${encodeURIComponent(id)}&status=eq.published&select=id,title,description,listing_type,category,price,currency,location,image_url,published_at&limit=1`)}
async function publicBusiness(key){const f=UUID.test(key)?`id=eq.${encodeURIComponent(key)}`:`slug=eq.${encodeURIComponent(key)}`;return sbGet(`businesses?${f}&status=eq.published&select=id,name,slug,short_description,description,cover_url,logo_url,address,rating_average,rating_count&limit=1`)}
function stripSeo(h){return h.replace(/<title>[\s\S]*?<\/title>/gi,'').replace(/<meta\b[^>]*(?:property\s*=\s*["']og:[^"']*["']|name\s*=\s*["'](?:description|twitter:[^"']*)["'])[^>]*>/gi,'').replace(/<link\b[^>]*rel\s*=\s*["']canonical["'][^>]*>/gi,'')}
function metaBlock({title,desc,url,img,type='website'}){return `<title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${esc(url)}"><meta property="og:type" content="${type}"><meta property="og:site_name" content="Хашури"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${esc(url)}">${img?`<meta property="og:image" content="${esc(img)}"><meta property="og:image:secure_url" content="${esc(img)}"><meta property="og:image:alt" content="${esc(title)}">`:''}<meta name="twitter:card" content="${img?'summary_large_image':'summary'}"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(desc)}">${img?`<meta name="twitter:image" content="${esc(img)}">`:''}`}
function listingMeta(l,id){const price=l.price!=null?`${l.price} ${l.currency==='GEL'?'₾':l.currency||''}`.trim():'';return metaBlock({title:`${l.title}${price?' — '+price:''} | Объявления Хашури`,desc:[l.description||'',price?`Цена: ${price}`:'',l.location?`📍 ${l.location}`:''].filter(Boolean).join(' · ').slice(0,220),url:`${ORIGIN}/classified/${id}`,img:l.image_url||'',type:'product'})}
function businessMeta(b){const slug=b.slug||b.id;return metaBlock({title:`${b.name} | Хашури`,desc:[b.short_description||b.description||`${b.name} — бизнес в Хашури`,b.address?`📍 ${b.address}`:'',b.rating_count?`⭐ ${Number(b.rating_average||0).toFixed(1)} (${b.rating_count})`:'' ].filter(Boolean).join(' · ').slice(0,220),url:`${ORIGIN}/business/${encodeURIComponent(slug)}`,img:b.cover_url||b.logo_url||'',type:'website'})}
function listingDeep(l,id){return `<script>(function(){var ID=${JSON.stringify(id)},TITLE=${JSON.stringify(l.title||'')};function o(){if(typeof kh36OpenOne==='function'){try{kh36OpenOne(ID);return true}catch(e){}}var a=[...document.querySelectorAll('[data-listing-id],[data-id],[onclick],article,button,div')];for(var x of a){var v=x.getAttribute('data-listing-id')||x.getAttribute('data-id')||'';if(v===ID||((x.textContent||'').includes(TITLE)&&x.getBoundingClientRect().height>80)){try{x.click();return true}catch(e){}}}return false}var n=0,t=setInterval(()=>{if(o()||++n>35)clearInterval(t)},300)})();</script>`}
function businessDeep(b){return `<script>(function(){var NAME=${JSON.stringify(b.name||'')};function o(){for(var x of document.querySelectorAll('article,button,a,div')){if((x.textContent||'').includes(NAME)&&x.getBoundingClientRect().height>80){try{x.click();return true}catch(e){}}}return false}var n=0,t=setInterval(()=>{if(o()||++n>35)clearInterval(t)},300)})();</script>`}
const filterBootstrap=`<script>(function(){function f(){var s=[...document.querySelectorAll('select')];for(var i=0;i<s.length-1;i++){var a=s[i],b=s[i+1],p=a.parentElement;for(var d=0;p&&d<6;d++,p=p.parentElement){if((p.textContent||'').includes('Объявления Хашури')&&p.querySelectorAll('select').length>=2)return{b}}}return null}function m(){if(document.querySelector('.kh54-inline-toggle'))return true;var x=f();if(!x)return false;var r=x.b.parentElement?.parentElement||x.b.parentElement||x.b,w=document.createElement('div');w.style.margin='10px 0';w.innerHTML='<button type="button" class="kh54-inline-toggle" style="width:100%;border:1px solid #d9dee7;background:#fff;border-radius:12px;padding:12px 14px;font-weight:800;font-size:16px;color:#263247">⚙️ Фильтры</button><div class="kh54-inline-panel" hidden style="margin-top:8px;padding:12px;border:1px solid #e3e7ed;border-radius:16px;background:#f8fafb"><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input name="kh54min" inputmode="decimal" placeholder="Цена от" style="width:100%;box-sizing:border-box;padding:11px;border:1px solid #d8dde5;border-radius:10px"><input name="kh54max" inputmode="decimal" placeholder="Цена до" style="width:100%;box-sizing:border-box;padding:11px;border:1px solid #d8dde5;border-radius:10px"></div><label style="display:flex;gap:8px;padding:8px 0"><input type="checkbox" name="kh54photo"> Только с фото</label><label style="display:flex;gap:8px;padding:8px 0"><input type="checkbox" name="kh54bargain"> Возможен торг</label><label style="display:flex;gap:8px;padding:8px 0"><input type="checkbox" name="kh54fresh"> Новые за 24 часа</label><select name="kh54sort" style="width:100%;padding:11px;border:1px solid #d8dde5;border-radius:10px"><option value="newest">Сначала новые</option><option value="price_asc">Цена: дешевле</option><option value="price_desc">Цена: дороже</option><option value="popular">Популярные</option><option value="oldest">Сначала старые</option></select></div>';r.insertAdjacentElement('afterend',w);w.querySelector('.kh54-inline-toggle').onclick=()=>{var p=w.querySelector('.kh54-inline-panel');p.hidden=!p.hidden};return true}var n=0,t=setInterval(()=>{if(m()||++n>180)clearInterval(t)},250);document.addEventListener('click',()=>setTimeout(m,120),true)})();</script>`;
module.exports=async(req,res)=>{try{const path=(req.url||'').split('?')[0];const assets=['/khashuri-v53.js','/khashuri-v54.js','/khashuri-v54-fallback.js','/khashuri-v55-business.js'];if(assets.includes(path)){const r=await fetch(RAW+path.slice(1)+'?cb=55.15');res.statusCode=r.status;res.setHeader('content-type','application/javascript; charset=utf-8');res.setHeader('cache-control','no-store, max-age=0, must-revalidate');return res.end(await r.text())}const upstream=await fetch(UPSTREAM,{headers:{'user-agent':'khashuri-marketplace-vercel-proxy/2.0'}});let html=await upstream.text();let hook='<script src="/khashuri-v53.js?v=53.3"></script><script src="/khashuri-v54.js?v=54.3"></script><script src="/khashuri-v54-fallback.js?v=54.2"></script><script src="/khashuri-v55-business.js?v=55.15"></script>'+filterBootstrap,meta='';const cm=path.match(/^\/classified\/([0-9a-f-]{36})$/i);if(cm&&UUID.test(cm[1])){const l=await publicListing(cm[1]);if(l){meta=listingMeta(l,cm[1]);hook+=listingDeep(l,cm[1])}else res.statusCode=404}const bm=path.match(/^\/business\/([^/?#]+)$/i);if(bm){const b=await publicBusiness(decodeURIComponent(bm[1]));if(b){meta=businessMeta(b);hook+=businessDeep(b)}else res.statusCode=404}if(meta){html=stripSeo(html).replace('</head>',meta+'</head>')}html=html.includes('</body>')?html.replace('</body>',hook+'</body>'):html+hook;if(!res.statusCode)res.statusCode=upstream.status;res.setHeader('content-type','text/html; charset=utf-8');res.setHeader('cache-control','no-store, max-age=0, must-revalidate');res.setHeader('x-content-type-options','nosniff');res.setHeader('x-khashuri-source','github-vercel-v55-15');res.end(html)}catch(e){res.statusCode=502;res.setHeader('content-type','text/plain; charset=utf-8');res.end('Khashuri upstream temporarily unavailable')}};