const SB='https://eppyjmtowtkxcwwhvwzp.supabase.co';
const KEY='sb_publishable_3oEkPaexOGYojb-9imVJjw_2SCQ7WRr';
module.exports=(req,res)=>{
res.setHeader('content-type','text/html; charset=utf-8');
res.setHeader('cache-control','no-store');
res.end(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>История оценок | Хашури</title><style>
:root{--teal:#11877c;--ink:#131c31;--muted:#70798b;--line:#e3e6eb;--bg:#f4f6f9}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif}.top{position:sticky;top:0;z-index:10;background:#fff;border-bottom:1px solid var(--line);padding:14px 18px;display:flex;align-items:center;gap:12px}.back{width:50px;height:50px;border:1px solid var(--line);background:#fff;border-radius:17px;font-size:28px}.top h1{font-size:24px;margin:0}.wrap{max-width:900px;margin:auto;padding:18px 16px 100px}.hero{background:linear-gradient(135deg,#10233c,#0c766e);color:#fff;border-radius:24px;padding:22px}.hero h2{margin:0 0 7px;font-size:29px}.hero p{margin:0;opacity:.86;line-height:1.45}.state{margin-top:14px;padding:18px;background:#fff;border:1px solid var(--line);border-radius:20px;color:var(--muted)}.card{margin-top:12px;background:#fff;border:1px solid var(--line);border-radius:20px;padding:16px}.head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.head b{font-size:19px}.date{font-size:12px;color:var(--muted)}.price{font-size:31px;font-weight:950;margin:12px 0 4px}.range{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:13px}.metric{padding:10px;background:#f7f8fa;border-radius:12px}.metric small{display:block;color:var(--muted);font-size:11px}.metric b{display:block;margin-top:3px}.actions{display:flex;gap:8px;margin-top:13px}.btn{border:0;border-radius:13px;padding:11px 14px;font-weight:850;background:var(--teal);color:#fff}.btn.alt{background:#fff;color:var(--ink);border:1px solid var(--line)}@media(max-width:650px){.top h1{font-size:21px}.grid{grid-template-columns:1fr 1fr}.price{font-size:28px}}
</style></head><body><header class="top"><button class="back" onclick="location.href='/valuation'">←</button><h1>📊 История оценок</h1></header><main class="wrap"><section class="hero"><h2>Сохранённые оценки</h2><p>Здесь накапливается история объекта и будущие данные для улучшения точности модели.</p></section><div id="app" class="state">Загружаю историю…</div></main><script>
const SB=${JSON.stringify(SB)},KEY=${JSON.stringify(KEY)};
const money=x=>'$'+Math.round(Number(x||0)).toLocaleString('en-US');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function session(){try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(!/^sb-.*-auth-token$/.test(k))continue;const x=JSON.parse(localStorage.getItem(k)||'null');const s=x?.access_token?x:(x?.currentSession||x?.session||x?.data?.session);if(s?.access_token)return s}}catch(e){}return null}
function pack(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function openVal(id){const s=session();if(!s)return;const h={apikey:KEY,Authorization:'Bearer '+s.access_token};const [vr,cr]=await Promise.all([fetch(SB+'/rest/v1/property_valuations?id=eq.'+encodeURIComponent(id)+'&select=*',{headers:h}),fetch(SB+'/rest/v1/valuation_comparables?valuation_id=eq.'+encodeURIComponent(id)+'&select=*',{headers:h})]);const v=(await vr.json())[0];if(!v)return alert('Оценка не найдена');const comps=await cr.json();const floors=(v.floor_areas||[]).map((f,i)=>({floor:f.floor||i+1,area:Number(f.area||0),condition:(v.floor_conditions||[])[i]?.condition||'average'}));const obj={...v,floors,comparables:(comps||[]).map(c=>({...c,asking_price:Number(c.asking_price||0),price_per_sqm_usd:Number(c.price_per_sqm||0),condition_label:c.condition_summary,comparison_role:c.metadata?.comparison_role,verified:c.metadata?.verified,city:c.metadata?.city,data_quality:Number(c.metadata?.data_quality||0),similarity_score:Number(c.similarity_score||0)}))};location.href='/valuation/result/'+id+'?data='+encodeURIComponent(pack(obj))+'&v=history'}
async function load(){const app=document.getElementById('app'),s=session();if(!s){app.innerHTML='<b style="color:#131c31">Войдите в кабинет, чтобы видеть историю оценок.</b><div style="margin-top:8px">Новые расчёты продолжат работать, но сохранение в облачную историю доступно авторизованным пользователям.</div>';return}try{const r=await fetch(SB+'/rest/v1/property_valuations?select=id,cadastral_code,city,address,house_area,land_area,estimated_value,market_low,market_high,confidence_score,confidence_label,created_at&order=created_at.desc&limit=50',{headers:{apikey:KEY,Authorization:'Bearer '+s.access_token}});if(!r.ok)throw new Error('HTTP '+r.status);const rows=await r.json();if(!rows.length){app.innerHTML='<b style="color:#131c31">История пока пустая.</b><div style="margin-top:8px">Сделайте новую оценку — после расчёта она появится здесь автоматически.</div>';return}app.className='';app.innerHTML=rows.map(v=>{const d=new Date(v.created_at);return '<article class="card"><div class="head"><div><b>'+esc(v.address||v.city||'Объект')+'</b><div class="date">'+d.toLocaleString('ru-RU')+'</div></div><span class="date">'+esc(v.cadastral_code||'')+'</span></div><div class="price">'+money(v.estimated_value)+'</div><div class="range">Диапазон '+money(v.market_low)+'–'+money(v.market_high)+'</div><div class="grid"><div class="metric"><small>Дом</small><b>'+Number(v.house_area||0)+' м²</b></div><div class="metric"><small>Земля</small><b>'+Number(v.land_area||0)+' м²</b></div><div class="metric"><small>Точность</small><b>'+Number(v.confidence_score||0)+'/100</b></div></div><div class="actions"><button class="btn" onclick="openVal(\''+v.id+'\')">Открыть</button><button class="btn alt" onclick="location.href=\'/valuation/new?mode=precise\'">Новая оценка</button></div></article>'}).join('')}catch(e){app.innerHTML='<b style="color:#a72d2d">Не удалось загрузить историю.</b><div style="margin-top:8px">Обновите страницу или войдите в кабинет заново.</div>'}}
load();
</script></body></html>`);
};