const SB='https://eppyjmtowtkxcwwhvwzp.supabase.co';
const KEY='sb_publishable_3oEkPaexOGYojb-9imVJjw_2SCQ7WRr';
module.exports=(req,res)=>{
res.statusCode=200;
res.setHeader('content-type','text/html; charset=utf-8');
res.setHeader('cache-control','no-store, max-age=0, must-revalidate');
res.end(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>История оценок | Хашури</title><style>
:root{--teal:#11877c;--ink:#131c31;--muted:#70798b;--line:#e3e6eb;--bg:#f4f6f9;--danger:#a72d2d}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif}.top{position:sticky;top:0;z-index:10;background:#fff;border-bottom:1px solid var(--line);padding:14px 18px;display:flex;align-items:center;gap:12px}.back{width:50px;height:50px;border:1px solid var(--line);background:#fff;border-radius:17px;font-size:28px}.top h1{font-size:24px;margin:0}.wrap{max-width:900px;margin:auto;padding:18px 16px 100px}.hero{background:linear-gradient(135deg,#10233c,#0c766e);color:#fff;border-radius:24px;padding:22px}.hero h2{margin:0 0 7px;font-size:29px}.hero p{margin:0;opacity:.86;line-height:1.45}.state{margin-top:14px;padding:18px;background:#fff;border:1px solid var(--line);border-radius:20px;color:var(--muted);line-height:1.45}.sync{display:flex;align-items:center;justify-content:space-between;gap:12px}.sync b{color:var(--ink)}.card{margin-top:12px;background:#fff;border:1px solid var(--line);border-radius:20px;padding:16px}.head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.head b{font-size:19px}.date{font-size:12px;color:var(--muted)}.badge{display:inline-block;margin-top:5px;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:850;background:#eef2f5;color:#5f6878}.badge.cloud{background:#e8f8f4;color:#0f7468}.price{font-size:31px;font-weight:950;margin:12px 0 4px}.range{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:13px}.metric{padding:10px;background:#f7f8fa;border-radius:12px}.metric small{display:block;color:var(--muted);font-size:11px}.metric b{display:block;margin-top:3px}.actions{display:flex;gap:8px;margin-top:13px;flex-wrap:wrap}.btn{border:0;border-radius:13px;padding:11px 14px;font-weight:850;background:var(--teal);color:#fff}.btn.alt{background:#fff;color:var(--ink);border:1px solid var(--line)}.error{color:var(--danger)}@media(max-width:650px){.top h1{font-size:21px}.grid{grid-template-columns:1fr 1fr}.price{font-size:28px}.sync{align-items:flex-start;flex-direction:column}}
</style></head><body><header class="top"><button class="back" onclick="location.href='/valuation'">←</button><h1>📊 История оценок</h1></header><main class="wrap"><section class="hero"><h2>Сохранённые оценки</h2><p>Здесь накапливается история объекта и будущие данные для улучшения точности модели.</p></section><div id="syncState" class="state">Проверяю синхронизацию…</div><div id="app" class="state">Загружаю историю…</div></main><script>
(function(){'use strict';
var SB=${JSON.stringify(SB)},KEY=${JSON.stringify(KEY)},app=document.getElementById('app'),syncState=document.getElementById('syncState');
function money(x){return '$'+Math.round(Number(x||0)).toLocaleString('en-US')}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}
function safe(v){try{return JSON.parse(v||'null')}catch(e){return null}}
function norm(x){if(!x)return null;if(x.access_token)return x;if(x.currentSession&&x.currentSession.access_token)return x.currentSession;if(x.session&&x.session.access_token)return x.session;if(x.data&&x.data.session&&x.data.session.access_token)return x.data.session;return null}
function getSession(){try{var d=norm(safe(localStorage.getItem('kh_session')));if(d)return d;for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i)||'';if(k.indexOf('sb-')===0&&k.slice(-11)==='-auth-token'){var s=norm(safe(localStorage.getItem(k)));if(s)return s}}}catch(e){}return null}
function localRows(){var a=[];try{for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i)||'';if(k.indexOf('valuation:local-')!==0)continue;var x=safe(localStorage.getItem(k));if(x&&x.id){x._local=true;a.push(x)}}}catch(e){}return a}
function timeout(ms){return new Promise(function(_,reject){setTimeout(function(){reject(new Error('timeout'))},ms)})}
async function fetchJson(url,opt){var r=await Promise.race([fetch(url,opt||{}),timeout(9000)]);if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}
function pack(obj){var bytes=new TextEncoder().encode(JSON.stringify(obj)),s='';for(var i=0;i<bytes.length;i++)s+=String.fromCharCode(bytes[i]);s=btoa(s).split('+').join('-').split('/').join('_');while(s.slice(-1)==='=')s=s.slice(0,-1);return s}
async function syncOne(v,s){var localId=String(v.id||'');if(!localId)return null;var known=localStorage.getItem('valuation:saved-id:'+localId);if(known)return known;try{var r=await fetchJson(SB+'/rest/v1/rpc/save_property_valuation',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:JSON.stringify({payload:Object.assign({},v,{id:localId})})});var id=String(r||'');if(id){localStorage.setItem('valuation:save:'+localId,'saved');localStorage.setItem('valuation:saved-id:'+localId,id)}return id||null}catch(e){localStorage.setItem('valuation:save:'+localId,'error');return null}}
async function openCloud(id){var s=getSession();if(!s){alert('Сначала войдите в кабинет.');return}var h={apikey:KEY,Authorization:'Bearer '+s.access_token};try{var both=await Promise.all([fetchJson(SB+'/rest/v1/property_valuations?id=eq.'+encodeURIComponent(id)+'&select=*',{headers:h}),fetchJson(SB+'/rest/v1/valuation_comparables?valuation_id=eq.'+encodeURIComponent(id)+'&select=*',{headers:h})]);var v=both[0]&&both[0][0];if(!v)return alert('Оценка не найдена');var fa=Array.isArray(v.floor_areas)?v.floor_areas:[],fc=Array.isArray(v.floor_conditions)?v.floor_conditions:[];var floors=fa.map(function(f,i){return {floor:f.floor||i+1,area:Number(f.area||0),condition:(fc[i]&&fc[i].condition)||'average'}});var obj=Object.assign({},v,{floors:floors,comparables:both[1]||[]});location.href='/valuation/result/'+encodeURIComponent(id)+'?data='+encodeURIComponent(pack(obj))+'&v=history'}catch(e){alert('Не удалось открыть оценку.')}}
function openLocal(id){var v=safe(localStorage.getItem('valuation:'+id));if(!v)return alert('Локальная оценка не найдена.');location.href='/valuation/result/'+encodeURIComponent(id)+'?data='+encodeURIComponent(pack(v))+'&v=history'}
window.openValuation=function(id,isLocal){isLocal?openLocal(id):openCloud(id)};
function render(rows,s){rows.sort(function(a,b){return new Date(b.created_at||0)-new Date(a.created_at||0)});if(!rows.length){app.innerHTML='<b>История пока пустая.</b><div style="margin-top:8px">Сделайте новую оценку — после расчёта она появится здесь автоматически.</div><div class="actions"><button class="btn" onclick="location.href=\'/valuation/new?mode=precise\'">Новая оценка</button></div>';return}app.className='';app.innerHTML=rows.map(function(v){var d=new Date(v.created_at||Date.now()),local=!!v._local;return '<article class="card"><div class="head"><div><b>'+esc(v.address||v.city||'Объект')+'</b><div class="date">'+d.toLocaleString('ru-RU')+'</div><span class="badge '+(local?'':'cloud')+'">'+(local?'📱 На устройстве':'☁️ В облаке')+'</span></div><span class="date">'+esc(v.cadastral_code||'')+'</span></div><div class="price">'+money(v.estimated_value)+'</div><div class="range">Диапазон '+money(v.market_low)+'–'+money(v.market_high)+'</div><div class="grid"><div class="metric"><small>Дом</small><b>'+Number(v.house_area||0)+' м²</b></div><div class="metric"><small>Земля</small><b>'+Number(v.land_area||0)+' м²</b></div><div class="metric"><small>Точность</small><b>'+Number(v.confidence_score||0)+'/100</b></div></div><div class="actions"><button class="btn" onclick="openValuation(\''+esc(v.id)+'\','+(local?'true':'false')+')">Открыть</button><button class="btn alt" onclick="location.href=\'/valuation/new?mode=precise\'">Новая оценка</button></div></article>'}).join('')}
async function load(){var locals=localRows(),s=getSession(),cloud=[];if(s&&s.access_token){syncState.innerHTML='<div class="sync"><div><b>☁️ Облачная история включена</b><div>Синхронизирую сохранённые на телефоне оценки с вашим аккаунтом.</div></div></div>';for(var i=0;i<locals.length;i++)await syncOne(locals[i],s);try{cloud=await fetchJson(SB+'/rest/v1/property_valuations?select=id,cadastral_code,city,address,house_area,land_area,estimated_value,market_low,market_high,confidence_score,confidence_label,created_at&order=created_at.desc&limit=50',{headers:{apikey:KEY,Authorization:'Bearer '+s.access_token}})}catch(e){syncState.innerHTML='<b class="error">Облачная история временно недоступна.</b><div>Локальные оценки остаются на устройстве.</div>'}}else{syncState.innerHTML='<b>📱 Сейчас оценки хранятся на этом устройстве.</b><div style="margin-top:6px">Войдите в кабинет на главной странице, чтобы новые и старые оценки сохранялись в Supabase и были доступны после смены телефона.</div>'}
var cloudIds={};(cloud||[]).forEach(function(x){cloudIds[String(x.id)]=1});var remaining=locals.filter(function(v){var mapped=localStorage.getItem('valuation:saved-id:'+v.id);return !(mapped&&cloudIds[mapped])});render((cloud||[]).concat(remaining),s)}
setTimeout(function(){if(app.textContent.indexOf('Загружаю историю')>=0)app.innerHTML='<b class="error">Загрузка заняла слишком много времени.</b><div>Обновите страницу.</div>'},12000);load();
})();
</script></body></html>`);
};